version: "3.9"
services:
  mysql:
    image: mysql:5
    hostname: ssmbootstrap_table-mysql5
    container_name: ssmbootstrap_table-mysql5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: "no"
    volumes:
      - ./.env/mysql/conf:/etc/mysql/conf.d
      - ./.env/mysql/data:/var/lib/mysql
